remote_theme: just-the-docs/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/cjluFree_logo_v1.9.0-beta.5.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false


# Aux links for the upper right navigation
aux_links:
  "量大自由 on GitHub":
    - "//github.com/ZWolken/cjluFree"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

color_scheme: nopurple
