blank_issues_enabled: false
contact_links:
  - name: 模块BUG错误报告(Bug report) / 插件功能请求(Feature request)
    url: https://github.com/zxy19/cjluFree/issues
    about: 注意：本仓库不负责模块的开发维护，点击该栏内的"Open"或“打开”按钮将前往原仓库的议题(issue)界面。
