name: 新版本请求(New version request)
description: 若需其他本体与模块版本的整合，请点击该栏内的"Get started"或“开始”按钮并按描述填写请求表单。
title: "新版本请求(New version request)"
labels: ["版本请求"]
assignees:
  - ZWolken
body:

  - type: input
    id: wecom-version
    attributes:
      label: 企业微信(WeCom) 本体APP版本
      placeholder: 例如： v4.0.0(Play version)
    validations:
      required: true
      
  - type: input
    id: cjlufree-version
    attributes:
      label: 量大自由 模块APP版本
      placeholder: 例如：v1.3.1-beta.2
    validations:
      required: true
      
  - type: textarea
    id: dowload-link
    attributes:
      label: 软件下载链接
      placeholder: |
        请提供 企业微信(WeCom) 本体APP的APK安装包文件（拖入即可），或者其下载方式（直链、网页链接、各大网盘皆可）。
        可直接提供 量大自由 模块APP相应版本的GitHub发布(Release)链接。
    validations:
      required: true
        
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: 注意事项
      description: 请阅读以下注意事项，否则该新LSPatch版本请求的议题(issue)将被忽略。
      options:
        - label: 我已知晓本程序仅供学习交流使用，严禁用于商业用途，请于24小时内删除。
          required: true
        - label: 我不会于微博、贴吧、钉钉、计量小梦等GFW内的公众平台上分享该仓库及程序内容。
          required: true
        - label: 我已知晓疫情防控人人有责。
          required: true
        - label: 我不应该使用此功能瞒报健康信息甚至归咎于本软件的使用。
          required: true
        - label: 我已知晓本程序随时可能在各种情况下失效。
          required: true
        - label: 我已知晓该仓库所有者并不会一定答复该新版本请求请求的议题(issue)。
          required: true
        - label: 我已填写本表格中要求的所有信息。
          required: true
